In [1]:
list1 = [1,2,7,3];


In [17]:
print(list1[-12])


IndexError: list index out of range

In [19]:
print(list1[-2])

7


In [21]:
print("List length: ",len(list1));

List length:  4


In [39]:
print(list1[-4:0])

[]


In [41]:
list2 = [1,2,7,3,4,5,6]

In [43]:
import numpy as np

In [47]:
a = np.array([1,2,3,4,5,6,7,8,9,0])

In [51]:
print(a,a.shape)

[1 2 3 4 5 6 7 8 9 0] (10,)


In [53]:
print(a.dtype)

int32


In [57]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [59]:
print(b.shape)

(3, 4)


In [63]:
b.ndarray.ndim()

AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

In [65]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
import matplotlib.pyplot as plt